[tool.poetry]
name = "otlet"
version = "0.2.1"
description = "CLI tool and wrapper for PyPI JSON Web API"
repository = "https://github.com/nhtnr/otlet"
license = "MIT"
authors = ["kevinshome <noah.tanner7@gmail.com>"]

[tool.poetry.scripts]
otlet = "otlet.otlet:main"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.931"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
